sudo: required
services:
  - docker

before_install:
  - docker build -t grzegorzpustulka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true grzegorzpustulka/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-474609891816"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCES_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
